//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JobPoster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPoster()
        {
            this.Applies = new HashSet<Apply>();
        }
    
        public int JobPostID { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [MaxLength(20, ErrorMessage = "Max 20 Characters Allowed")]
        [MinLength(6, ErrorMessage = "Password must be at least 6 characters ")]
        public string UserPass { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Compare("UserPass", ErrorMessage = "Passwords Mismatch,Please Re-Enter")]
        [Display(Name = "Confirm Password")]
        public string ConfirmPass { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string JobName { get; set; }
        public string JobDesc { get; set; }
        public short WorkDays { get; set; }
        public long Salary { get; set; }
        public string Skills { get; set; }
        public Nullable<short> Age { get; set; }
        public string Gender { get; set; }
        
        public long ConNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apply> Applies { get; set; }

        //public static implicit operator int(JobPoster v)
        //{
        //    throw new NotImplementedException();
        //}
    }
}
